# Generated by Django 2.2.6 on 2019-10-24 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Batz_API', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='contact_phonenumber',
            field=models.CharField(default='000000000000', max_length=50),
        ),
    ]
