# Generated by Django 2.2.6 on 2019-10-26 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Batz_API', '0002_contact_contact_phonenumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_severity', models.CharField(max_length=50)),
                ('log_date', models.DateTimeField(auto_now_add=True)),
                ('log_data', models.CharField(max_length=256)),
            ],
        ),
    ]
